# Generated by Django 2.1 on 2019-08-06 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mduuser',
            name='favorite_team',
            field=models.CharField(default='Liverpool', max_length=100),
            preserve_default=False,
        ),
    ]
